export const locationConstants = {

    GET_LOCATION_REQUEST: 'GET_LOCATION_REQUEST',
    GET_LOCATION_SUCCESS: 'GET_LOCATION_SUCCESS',
    GET_LOCATION_FAILURE: 'GET_LOCATION_FAILURE',

    GET_LOCATION_LIST_REQUEST: 'GET_LOCATION_LIST_REQUEST',
    GET_LOCATION_LIST_SUCCESS: 'GET_LOCATION_LIST_SUCCESS',
    GET_LOCATION_LIST_FAILURE: 'GET_LOCATION_LIST_FAILURE',

    INSERT_LOCATION_REQUEST: 'INSERT_LOCATION_REQUEST',
    INSERT_LOCATION_SUCCESS: 'INSERT_LOCATION_SUCCESS',
    INSERT_LOCATION_FAILURE: 'INSERT_LOCATION_FAILURE',

    UPDATE_LOCATION_REQUEST: 'UPDATE_LOCATION_REQUEST',
    UPDATE_LOCATION_SUCCESS: 'UPDATE_LOCATION_SUCCESS',
    UPDATE_LOCATION_FAILURE: 'UPDATE_LOCATION_FAILURE',

    REMOVE_LOCATION_REQUEST: 'REMOVE_LOCATION_REQUEST',
    REMOVE_LOCATION_SUCCESS: 'REMOVE_LOCATION_SUCCESS',
    REMOVE_LOCATION_FAILURE: 'REMOVE_LOCATION_FAILURE',
};