export const personConstants = {

    GET_PERSON_REQUEST: 'GET_PERSON_REQUEST',
    GET_PERSON_SUCCESS: 'GET_PERSON_SUCCESS',
    GET_PERSON_FAILURE: 'GET_PERSON_FAILURE',

    GET_PERSON_PAGE_REQUEST: 'GET_PERSON_PAGE_REQUEST',
    GET_PERSON_PAGE_SUCCESS: 'GET_PERSON_PAGE_SUCCESS',
    GET_PERSON_PAGE_FAILURE: 'GET_PERSON_PAGE_FAILURE',

    GET_PERSON_LIST_REQUEST: 'GET_PERSON_LIST_REQUEST',
    GET_PERSON_LIST_SUCCESS: 'GET_PERSON_LIST_SUCCESS',
    GET_PERSON_LIST_FAILURE: 'GET_PERSON_LIST_FAILURE',

    INSERT_PERSON_REQUEST: 'INSERT_PERSON_REQUEST',
    INSERT_PERSON_SUCCESS: 'INSERT_PERSON_SUCCESS',
    INSERT_PERSON_FAILURE: 'INSERT_PERSON_FAILURE',

    UPDATE_PERSON_REQUEST: 'UPDATE_PERSON_REQUEST',
    UPDATE_PERSON_SUCCESS: 'UPDATE_PERSON_SUCCESS',
    UPDATE_PERSON_FAILURE: 'UPDATE_PERSON_FAILURE',

    PARTIAL_UPDATE_PERSON_REQUEST: 'PARTIAL_UPDATE_PERSON_REQUEST',
    PARTIAL_UPDATE_PERSON_SUCCESS: 'PARTIAL_UPDATE_PERSON_SUCCESS',
    PARTIAL_UPDATE_PERSON_FAILURE: 'PARTIAL_UPDATE_PERSON_FAILURE',

    REMOVE_PERSON_REQUEST: 'REMOVE_PERSON_REQUEST',
    REMOVE_PERSON_SUCCESS: 'REMOVE_PERSON_SUCCESS',
    REMOVE_PERSON_FAILURE: 'REMOVE_PERSON_FAILURE',
};