export const companyConstants = {

    GET_COMPANY_REQUEST: 'GET_COMPANY_REQUEST',
    GET_COMPANY_SUCCESS: 'GET_COMPANY_SUCCESS',
    GET_COMPANY_FAILURE: 'GET_COMPANY_FAILURE',

    GET_COMPANY_LIST_REQUEST: 'GET_COMPANY_LIST_REQUEST',
    GET_COMPANY_LIST_SUCCESS: 'GET_COMPANY_LIST_SUCCESS',
    GET_COMPANY_LIST_FAILURE: 'GET_COMPANY_LIST_FAILURE',

    INSERT_COMPANY_REQUEST: 'INSERT_COMPANY_REQUEST',
    INSERT_COMPANY_SUCCESS: 'INSERT_COMPANY_SUCCESS',
    INSERT_COMPANY_FAILURE: 'INSERT_COMPANY_FAILURE',

    UPDATE_COMPANY_REQUEST: 'UPDATE_COMPANY_REQUEST',
    UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
    UPDATE_COMPANY_FAILURE: 'UPDATE_COMPANY_FAILURE',

    REMOVE_COMPANY_REQUEST: 'REMOVE_COMPANY_REQUEST',
    REMOVE_COMPANY_SUCCESS: 'REMOVE_COMPANY_SUCCESS',
    REMOVE_COMPANY_FAILURE: 'REMOVE_COMPANY_FAILURE',
};