export const deviceConstants = {

    GET_DEVICE_REQUEST: 'GET_DEVICE_REQUEST',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    GET_DEVICE_FAILURE: 'GET_DEVICE_FAILURE',

    GET_DEVICE_LIST_REQUEST: 'GET_DEVICE_LIST_REQUEST',
    GET_DEVICE_LIST_SUCCESS: 'GET_DEVICE_LIST_SUCCESS',
    GET_DEVICE_LIST_FAILURE: 'GET_DEVICE_LIST_FAILURE',

    INSERT_DEVICE_REQUEST: 'INSERT_DEVICE_REQUEST',
    INSERT_DEVICE_SUCCESS: 'INSERT_DEVICE_SUCCESS',
    INSERT_DEVICE_FAILURE: 'INSERT_DEVICE_FAILURE',

    UPDATE_DEVICE_REQUEST: 'UPDATE_DEVICE_REQUEST',
    UPDATE_DEVICE_SUCCESS: 'UPDATE_DEVICE_SUCCESS',
    UPDATE_DEVICE_FAILURE: 'UPDATE_DEVICE_FAILURE',

    REMOVE_DEVICE_REQUEST: 'REMOVE_DEVICE_REQUEST',
    REMOVE_DEVICE_SUCCESS: 'REMOVE_DEVICE_SUCCESS',
    REMOVE_DEVICE_FAILURE: 'REMOVE_DEVICE_FAILURE',
};